import { contextBridge, ipcRenderer, webUtils } from "electron";

contextBridge.exposeInMainWorld("cicd", {
  platform: process.platform,
  checkPrerequisites: () => ipcRenderer.invoke("check-prerequisites"),
  selectDirectory: () => ipcRenderer.invoke("select-directory"),
  selectFiles: (extensions: string[]) => ipcRenderer.invoke("select-files", extensions),
  selectActionDocument: () => ipcRenderer.invoke("select-action-document"),
  selectEvidenceImages: () => ipcRenderer.invoke("select-evidence-images"),
  captureAppWindow: () => ipcRenderer.invoke("capture-app-window"),
  captureScreenRegion: () => ipcRenderer.invoke("capture-screen-region"),
  saveEvidenceImage: (payload: unknown) => ipcRenderer.invoke("save-evidence-image", payload),
  saveEvidenceImages: (payload: unknown) => ipcRenderer.invoke("save-evidence-images", payload),
  loadKnowledge: () => ipcRenderer.invoke("load-knowledge"),
  installKnowledgePackage: (filePath: string) => ipcRenderer.invoke("install-knowledge-package", filePath),
  checkKnowledgeUpdate: (payload: unknown) => ipcRenderer.invoke("check-knowledge-update", payload),
  installKnowledgeUpdate: (payload: unknown) => ipcRenderer.invoke("install-knowledge-update", payload),
  rollbackKnowledgePackage: () => ipcRenderer.invoke("rollback-knowledge-package"),
  getAppUpdateStatus: () => ipcRenderer.invoke("get-app-update-status"),
  checkAppUpdate: () => ipcRenderer.invoke("check-app-update"),
  restartToInstallUpdate: () => ipcRenderer.invoke("restart-to-install-update"),
  saveActionPlanText: (payload: unknown) => ipcRenderer.invoke("save-action-plan-text", payload),
  getPathForFile: (file: File) => webUtils?.getPathForFile(file) ?? (file as File & { path?: string })?.path ?? "",
  scanRepositories: (basePath: string) => ipcRenderer.invoke("scan-repositories", basePath),
  syncRepository: (repoPath: string) => ipcRenderer.invoke("sync-repository", repoPath),
  cleanRepositoryMetadata: (repoPath: string) => ipcRenderer.invoke("clean-repository-metadata", repoPath),
  cloneRepository: (payload: unknown) => ipcRenderer.invoke("clone-repository", payload),
  prepareRfcDraft: (payload: unknown) => ipcRenderer.invoke("prepare-rfc-draft", payload),
  getDraftSummary: (payload: unknown) => ipcRenderer.invoke("get-draft-summary", payload),
  commitRfcLocal: (payload: unknown) => ipcRenderer.invoke("commit-rfc-local", payload),
  pushRfcBranch: (payload: unknown) => ipcRenderer.invoke("push-rfc-branch", payload),
  undoRfcLocalCommit: (payload: unknown) => ipcRenderer.invoke("undo-rfc-local-commit", payload),
  finalizeRfc: (payload: unknown) => ipcRenderer.invoke("finalize-rfc", payload),
  inspectArtifacts: (filePaths: string[]) => ipcRenderer.invoke("inspect-artifacts", filePaths),
  exportEvidenceDocx: (payload: unknown) => ipcRenderer.invoke("export-evidence-docx", payload),
  exportEvidencePdf: (payload: unknown) => ipcRenderer.invoke("export-evidence-pdf", payload),
  backupUserData: (payload: unknown) => ipcRenderer.invoke("backup-user-data", payload),
  clearUserFiles: () => ipcRenderer.invoke("clear-user-files"),
  deleteLocalFile: (path: string) => ipcRenderer.invoke("delete-local-file", path),
  openExternal: (url: string) => ipcRenderer.invoke("open-external", url),
  showItemInFolder: (path: string) => ipcRenderer.invoke("show-item-in-folder", path)
});
