const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("cicd", {
  checkPrerequisites: () => ipcRenderer.invoke("check-prerequisites"),
  selectDirectory: () => ipcRenderer.invoke("select-directory"),
  selectFiles: (extensions) => ipcRenderer.invoke("select-files", extensions),
  selectActionDocument: () => ipcRenderer.invoke("select-action-document"),
  selectEvidenceImages: () => ipcRenderer.invoke("select-evidence-images"),
  captureAppWindow: () => ipcRenderer.invoke("capture-app-window"),
  captureScreenRegion: () => ipcRenderer.invoke("capture-screen-region"),
  saveEvidenceImage: (payload) => ipcRenderer.invoke("save-evidence-image", payload),
  saveEvidenceImages: (payload) => ipcRenderer.invoke("save-evidence-images", payload),
  loadKnowledge: () => ipcRenderer.invoke("load-knowledge"),
  installKnowledgePackage: (filePath) => ipcRenderer.invoke("install-knowledge-package", filePath),
  rollbackKnowledgePackage: () => ipcRenderer.invoke("rollback-knowledge-package"),
  saveActionPlanText: (payload) => ipcRenderer.invoke("save-action-plan-text", payload),
  getPathForFile: (file) => webUtils?.getPathForFile(file) ?? file?.path ?? "",
  scanRepositories: (basePath) => ipcRenderer.invoke("scan-repositories", basePath),
  cloneRepository: (payload) => ipcRenderer.invoke("clone-repository", payload),
  prepareRfcDraft: (payload) => ipcRenderer.invoke("prepare-rfc-draft", payload),
  getDraftSummary: (payload) => ipcRenderer.invoke("get-draft-summary", payload),
  commitRfcLocal: (payload) => ipcRenderer.invoke("commit-rfc-local", payload),
  pushRfcBranch: (payload) => ipcRenderer.invoke("push-rfc-branch", payload),
  undoRfcLocalCommit: (payload) => ipcRenderer.invoke("undo-rfc-local-commit", payload),
  finalizeRfc: (payload) => ipcRenderer.invoke("finalize-rfc", payload),
  inspectArtifacts: (filePaths) => ipcRenderer.invoke("inspect-artifacts", filePaths),
  exportEvidenceDocx: (payload) => ipcRenderer.invoke("export-evidence-docx", payload),
  exportEvidencePdf: (payload) => ipcRenderer.invoke("export-evidence-pdf", payload),
  backupUserData: (payload) => ipcRenderer.invoke("backup-user-data", payload),
  clearUserFiles: () => ipcRenderer.invoke("clear-user-files"),
  deleteLocalFile: (path) => ipcRenderer.invoke("delete-local-file", path),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  showItemInFolder: (path) => ipcRenderer.invoke("show-item-in-folder", path)
});
